server:
  port: 8081

jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      show_sql: false
      use_sql_comments: false
      format_sql: true
    database: h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true
    username: MST_ADM
    password: MST_ADM
    driver-class-name: org.h2.Driver